cmd_list.rs: use FSCK_FIX_yes
Commit f3b51d2bbf68 ("bcachefs: fix_errors option is now a proper enum")
in bcachefs.git changed FSCK_OPT_YES to FSCK_FIX_yes. Update the rust
code to reflect this.

Fixes the following compile error:

error[E0599]: no variant or associated item named `FSCK_OPT_YES` found for enum `fsck_err_opts` in the current scope
   --> src/cmd_list.rs:141:66
    |
141 |         opt_set!(fs_opts, fix_errors,   bcachefs::fsck_err_opts::FSCK_OPT_YES as u8);
    |                                                                  ^^^^^^^^^^^^ variant or associated item not found in `fsck_err_opts`

Fixes: 691b5e391ab3 ("Update bcachefs sources to e14d7c7195 bcachefs: Compression levels")
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>